name = "wellfusion-proxy"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "96efe5d050be46cca991dc02491502ca", preview_id = "4daadfc8c22742acab5fb924892f76a9" },
]
